# Generated by Django 3.2.25 on 2024-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=500)),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
            ],
        ),
    ]
